services:
  orchestrator:
    build: .
    container_name: orchestrator
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - strategy-engine
      - nlu-service
      - llm-phraser

  strategy-engine:
    build: ./microservices/strategy-engine
    container_name: strategy-engine
    ports:
      - "8001:8000"

  nlu-service:
    build: ./microservices/nlu-service
    container_name: nlu-service
    ports:
      - "8002:8000"

  llm-phraser:                    # <--- NEW
    build: ./microservices/llm-phraser
    container_name: llm-phraser
    ports:
      - "8003:8000" 
    environment:
      - GROQ_API_KEY=${GROQ_API_KEY}        # browser URL â†’ http://localhost:8003/docs

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
